version: "3"
services:
  db:
    image: arm64v8/mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - ./configdb:/data/configdb
  app:
    platform: linux/x86_64
    build:
      context: .
#    env_file: .env.development
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/app
      - app-data:/stamps/vendor/bundle:cached
      - node-data:/stamps/node_modules:cached
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  mongodb-data:
    driver: local
  app-data:
    driver: local
  node-data:
    driver: local
